language: cpp

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls --use-mirrors

script:
  - g++ -g -O0 -coverage -o prog1 prog1.cpp && ./prog1
  - ls -l 
   

after_success:
  - coveralls --verbose
