language: cpp

compiler:
  - gcc

before_install:
  - git clone https://github.com/eddyxu/cpp-coveralls.git
  - cd cpp-coveralls
  - sudo python setup.py install
  - cd ..

script:
  - cmake . && make 
  - ./prog1
  - ls -l
  - ls -al CMakeFiles/prog1.dir  
  - gcov -o CMakeFiles/prog1.dir/prog1.cpp.o x
  - ls -al   

after_success:
  - coveralls --verbose
