language: cpp

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls --use-mirrors

script:
  - cmake . && make && ./prog1 
  - mkdir aa && cd aa && g++ -coverage -o prog2 ../prog1.cpp && ./prog2 && cd ..
  - ls -l && ls -l CMakeFiles/ && ls -l CMakeFiles/prog1.dir&& ls -al aa/
   

after_success:
  - coveralls --verbose 
